Ruby on Rails/book_store/config/routes.rb
Rails.application.routes.draw do

  root to: 'high_voltage/pages#show', id: 'home'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  authenticated :user do
    resources :books do
      resources :copies do
        post :change_state, on: :member
        post :prolongate, on: :member
      end
    end
  end
end

Ruby on Rails/book_store/app/models/book.rb
class Book < ActiveRecord::Base
  has_many :copies, dependent: :destroy
  after_create :create_copies

  private

  def create_copies
    current_copies_count = copies.count
    (copies_count - current_copies_count).times do
      copies.create
    end
  end
end

Ruby on Rails/book_store/app/models/borrow.rb
class Borrow < ActiveRecord::Base
  belongs_to :user
  belongs_to :copy
  has_many :penalties, dependent: :destroy
end

Ruby on Rails/book_store/app/models/copy.rb
class Copy < ActiveRecord::Base
  belongs_to :book
  has_many :borrows, dependent: :destroy

  attr_accessor :user_id

  before_create :initial_state

  state_machine :state do
    after_transition :free => :borrowed, do: :create_borrow
    after_transition :free => :reserved, do: :create_reservation
    after_transition :reserved => :borrowed, do: :reservation_done
    after_transition :reserved => :free, do: :reservation_cancel
    after_transition :borrowed => :free, do: :borrow_done

    event :borrow do
      transition [:free, :reserved] => :borrowed
    end
    event :reserve do
      transition [:free, :borrowed] => :reserved
    end
    event :return do
      transition :borrowed => :free
    end
    event :cancel do
      transition :reserved => :free
    end
    event :report do
      transition :borrowed => :repair_needed
    end
    event :send_to_repair do
      transition :repair_needed => :in_repair
    end
    event :discard do
      transition [:repair_needed, :in_repair] => :discarded
    end
  end

  def prolongate
    borrows.where(user_id: user_id).last.update(return_planned_at: 7.days.from_now)
  end

  private

  def initial_state
    self.state = 'free'
  end

  def create_borrow
    borrows.create(user_id: user_id, borrowed_at: Time.now, return_planned_at: 7.days.from_now, reservation: false)
  end

  def create_reservation
    borrow = create_borrow
    borrow.update(reservation: true)
  end

  def reservation_done
    borrows.last.update(borrowed_at: Time.now, return_planned_at: 7.days.from_now, reservation: false)
  end

  def reservation_cancel
    borrows.last.destroy
  end

  def borrow_done
    borrows.where(returned_at: nil, reservation: false).last.update(returned_at: Time.now)
  end

end

Ruby on Rails/book_store/app/models/penalty.rb
class Penalty < ActiveRecord::Base
  belongs_to :borrow
  has_one :user, through: :borrow
end

Ruby on Rails/book_store/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :borrows, dependent: :destroy
  has_many :copies, through: :borrows
  has_many :penalties, through: :borrows
end

Ruby on Rails/book_store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  include HttpAcceptLanguage::AutoLocale

  protected

  def configure_permitted_parameters
    keys = [:name, :surname, :pesel, :address, :worker] if current_user && (current_user.admin? || current_user.worker?)
    # keys.insert(:worker) if current_user && current_user.admin?
    devise_parameter_sanitizer.permit(:sign_up, keys: keys)
  end
end

Ruby on Rails/book_store/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :publisher, :author, :copies_count, :genre)
    end
end

Ruby on Rails/book_store/app/controllers/copies_controller.rb
class CopiesController < ApplicationController
  def change_state
    @copy = Copy.find(params[:id])
    @copy.user_id = params[:user_id] || current_user.id
    @copy.fire_state_event(params[:event].to_sym)
    redirect_to @copy.book
  end

  def prolongate
    @copy = Copy.find(params[:id])
    @copy.user_id = params[:user_id] || current_user.id
    @copy.prolongate
    redirect_to root_path
  end
end

Ruby on Rails/book_store/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  skip_before_filter :require_no_authentication, only: [:new, :create, :cancel]

  # GET /resource/sign_up
  def new
    if !current_user || (!current_user.admin? && !current_user.worker?)
      flash[:error] = I18n.t("access_denied")
      redirect_to root_path
    else
      super
    end
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # Do not auto login
  def sign_up(resource_name, resource)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

Ruby on Rails/book_store/app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? 'active' : ""
  end
end

Ruby on Rails/book_store/app/helpers/books_helper.rb
module BooksHelper
end

Ruby on Rails/book_store/app/helpers/borrows_helper.rb
module BorrowsHelper
end

Ruby on Rails/book_store/app/helpers/copies_helper.rb
module CopiesHelper
end

Ruby on Rails/book_store/app/helpers/penalties_helper.rb
module PenaltiesHelper
end

Ruby on Rails/book_store/app/views/books/_form.html.erb
<%= form_for(@book, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @book.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h4>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :publisher, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :publisher, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :author, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :author, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :genre, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :genre, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :copies_count, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :copies_count, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

Ruby on Rails/book_store/app/views/books/edit.html.erb
<div class="page-header">
  <%= link_to books_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @book, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing book</h1>
</div>

<%= render 'form' %>

Ruby on Rails/book_store/app/views/books/index.html.erb
<div class="page-header">
  <% if current_user.worker? %>
    <%= link_to new_book_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Book
    <% end %>
  <% end %>
  <h1>Listing books</h1>
</div>

<%= search_form_for(@q, html: { class: "form-inline", role: "form" }) do |f| %>
  <div class="form-group">
    <%= f.search_field :title_or_publisher_or_author_or_genre_cont, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
  <%= link_to "Reset", request.path, class: "btn btn-danger" %>
<% end %>
<br>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Publisher</th>
        <th>Author</th>
        <th>Genre</th>
        <th></th>
        <% if current_user.worker? %>
          <th></th>
          <th></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @books) do |book| %>
        <td><%= book.title %></td>
        <td><%= book.publisher %></td>
        <td><%= book.author %></td>
        <td><%= book.genre %></td>
        <td><%= link_to 'Show', book %></td>
        <% if current_user.worker? %>
          <td><%= link_to 'Edit', edit_book_path(book) %></td>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

Ruby on Rails/book_store/app/views/books/new.html.erb
<div class="page-header">
  <%= link_to books_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New book</h1>
</div>

<%= render 'form' %>

Ruby on Rails/book_store/app/views/books/show.html.erb
<div class="page-header">
  <%= link_to books_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <% if current_user.worker? %>
    <%= link_to edit_book_path(@book), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Edit
    <% end %>
  <% end %>
  <h1>Show book</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @book.title %></dd>

  <dt>Publisher:</dt>
  <dd><%= @book.publisher %></dd>

  <dt>Author:</dt>
  <dd><%= @book.author %></dd>

  <dt>Genre:</dt>
  <dd><%= @book.genre %></dd>

</dl>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th>State</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% index = 0 %>
      <%= content_tag_for(:tr, @book.copies) do |copy| %>
        <td><%= index += 1 %></td>
        <td><%= copy.state %></td>
        <% if !current_user.worker? %>
          <td>
            <%= link_to 'Reserve', change_state_book_copy_path(@book, copy, event: 'reserve'), method: :post if copy.free? || copy.borrowed? %>
            <%= link_to 'Cancel', change_state_book_copy_path(@book, copy, event: 'cancel'), method: :post if copy.reserved? && current_user.borrows.where(copy_id: copy.id).present? %>
          </td>
        <% else %>
          <td>
            <%= link_to 'Borrow', '', data: { toggle: 'modal', target: '#myModal', copy_id: copy.id } if copy.free? %>
            <% copy.state_events.reject { |el| el == :borrow }.each do |event| %>
              <%= link_to event.to_s.humanize, change_state_book_copy_path(@book, copy, event: event.to_s), method: :post %>
            <% end %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Borrow</h4>
      </div>
      <div class="modal-body">
        <%= form_tag(change_state_book_copy_path(@book, 'copyId', event: 'borrow'), class: "form-horizontal", role: "form") do |f| %>
          <div class="form-group">
            <%= label_tag :user_id, nil, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= text_field_tag :user_id, nil, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= submit_tag nil, class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  //triggered when modal is about to be shown
  $('#myModal').on('show.bs.modal', function(e) {
      //get data-id attribute of the clicked element
      var copyId = $(e.relatedTarget).data('copy-id');

      //populate the textbox
      var action = $(e.currentTarget).find('form').attr('action');
      action = action.replace('copyId', copyId);
      $(e.currentTarget).find('form').attr('action', action);
  });
</script>

Ruby on Rails/book_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>BookStore</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "BookStore", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class=<%= active_class(root_path) %>><%= link_to "Home", root_path %></li>
          <% if current_user %>
            <li class=<%= active_class(destroy_user_session_path) %>><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            <% if current_user.admin || current_user.worker? %>
              <li class=<%= active_class(new_user_registration_path) %>><%= link_to "Add user", new_user_registration_path %></li>
              <li class=<%= active_class(new_book_path) %>><%= link_to "Add book", new_book_path %></li>
              <li class=<%= active_class(books_path) %>><%= link_to "Books", books_path %></li>
            <% else %>
              <li class=<%= active_class(books_path) %>><%= link_to "Books", books_path %></li>
            <% end %>
          <% else %>
            <li class=<%= active_class(new_user_session_path) %>><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <p class="navbar-text">
              <%= t('hello') %>
              <%= current_user.email %>
            </p>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

Ruby on Rails/book_store/app/views/pages/home.html.erb
<% if current_user && current_user.worker? %>
<h4>Statystyka biblioteki:</h4>
<p>Ilość książek w bazie: <%= Book.count %>
<p>Ogólna liczba wypożyczeń: <%= Borrow.count %></p>
</p>
<% elsif current_user && !current_user.admin? %>
<h4>Moje wypożyczenia:</h4>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Status</th>
        <th>Wypożyczono</th>
        <th>Do oddania</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, current_user.copies.with_states(:borrowed, :reserved).includes(:book, :borrows).where("borrows.returned_at IS NULL")) do |copy| %>
        <td><%= copy.book.title %></td>
        <td><%= copy.state %></td>
        <td><%= copy.borrows.where(user_id: current_user.id).last.borrowed_at %></td>
        <td><%= copy.borrows.where(user_id: current_user.id).last.return_planned_at %></td>
        <td><%= link_to 'Prolongata', prolongate_book_copy_path(copy.book, copy), method: :post if copy.borrowed? %></td>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
<h4>Witamy w systemie obsługi biblioteki, BookStore!</h4>
<p>Dzięki systemowi BookStore przyspieszymy i ułatwimy wypożyczanie książek naszym klientom. Skrócimy czas wypożyczeń do minimum. Dzięki systemowi nie będzie już problemu z rezerwacją książek, oraz jej prolongatą.</p>
<% end %>